---
- name: testing RHV with Ansible
  hosts: localhost
  
  tasks:
  - name: Obtain SSO token
    ovirt_auth:
      url: "{{ lookup('env','OVIRT_URL') }}"
      username: "{{ lookup('env','OVIRT_USERNAME') }}"
      password: "{{ lookup('env','OVIRT_PASSWORD') }}"
      ca_file: "{{ lookup('env','OVIRT_CAFILE') }}"
      state: present

  - name: Logout from oVirt
    ovirt_auth:
      ovirt_auth: "{{ ovirt_auth }}"
      state: absent
