---
- hosts: Gluster[0] 
  vars:
    MASTER_VOL: rhv-sd1
    PRIMARY_SLAVE_HOST: dr-gluster01.example.com
    SLAVE_VOL: rhv-sd1-dr
    
  tasks:
    - name: Force geo-replication to secondary site
      command: python /usr/local/bin/schedule_georep.py {{ MASTER_VOL }} {{ PRIMARY_SLAVE_HOST }} {{ SLAVE_VOL }} 

- hosts: Gluster
  vars:
    ansible_user: root
 
  tasks:
    - name: Stop glusterd to simulate failure
      systemd:
        state: stopped
        name: glusterd

    - name: Kill running glusterfs processes
      command: pkill glusterfs

- hosts: RHVM
  vars:
    ansible_user: root
  
  tasks:
    - name: Stop ovirt-engine to simulate failure
      systemd:
        state: stopped
        name: ovirt-engine
