---
- hosts: Gluster[0] 
  vars:
    MASTER_VOL: rhv-sd1
    PRIMARY_SLAVE_HOST: dr-gluster01.example.com
    SLAVE_VOL: rhv-sd1-dr
    
  tasks:
    - name: Force geo-replication to secondary site
      command: python /usr/local/bin/schedule_georep.py {{ MASTER_VOL }} {{ PRIMARY_SLAVE_HOST }} {{ SLAVE_VOL }} 

    # TODO: setting to r/o should be done when bringing services up again instead of doing it here
    - name: Set volume to read-only
      command: gluster volume set {{ MASTER_VOL }} features.read-only on 

- hosts: Gluster
  vars:
    ansible_user: root
 
  tasks:
    - name: Stop glusterd to simulate failure
      systemd:
        state: stopped
        name: glusterd

    - name: Kill running glusterfs processes
      command: pkill glusterfs

- hosts: RHVM
  vars:
    ansible_user: root
  
  tasks:
    - name: Stop ovirt-engine to simulate failure
      systemd:
        state: stopped
        name: ovirt-engine
 
- hosts: RHVH
  vars:
    ansible_user: root

  tasks:
    - name: reboot host
      shell: sleep 10 && /sbin/shutdown -r now
      async: 300
      poll: 0
