---
- hosts: Gluster
  vars:
    ansible_user: root
 
  tasks:
    - name: Start glusterd
      systemd:
        state: started
        name: glusterd

    - name: Pause to ensure glusterd is started
      pause:
        seconds: 5

    - name: Restart glusterfssharedstorage service
      systemd:
        state: restarted
        name: glusterfssharedstorage


- hosts: RHVM
  vars:
    ansible_user: root
  
  tasks:
    - name: Start ovirt-engine
      systemd:
        state: started
        name: ovirt-engine
