---
- hosts: Gluster

  tasks:
  - name: Ensure Gluster is running on primary site
    systemd:
      state: started
      name: glusterd
    tags: clean_engine

- hosts: Gluster[0]

  tasks:
  - name: Prepare Gluster on Primary Site
    import_role:
      name: gluster
      tasks_from: gluster-prepare-failback.yml
    tags: clean_engine

