---
- hosts: DR-Gluster[0]

  tasks:
  - name: Failback storage
    import_role:
      name: gluster
      tasks_from: failback.yml
    tags: fail_back

- hosts: Gluster[0]

  tasks:
  - name: Set volume to read-write
    command: gluster volume set rhv-sd1 features.read-only off
    tags: fail_back

