---
- hosts: Gluster

  tasks:
  - name: Ensure Gluster is running on primary site
    systemd:
      state: started
      name: glusterd

  - name: Pause to ensure glusterd is started
    pause:
      seconds: 5

  # Required for demo environment as the failure simulation
  # only stops / kills gluster services
  - name: Restart glusterfssharedstorage service
    systemd:
      state: restarted
      name: glusterfssharedstorage

- hosts: Gluster[0]

  tasks:
  - name: Prepare Gluster on Primary Site
    import_role:
      name: gluster
      tasks_from: gluster-prepare-failback.yml

