---
- hosts: DR-Gluster
  vars:
    ansible_user: root

  tasks:
    - name: Ensure glusterd is active
      systemd:
        state: started
        name: glusterd

- hosts: DR-Gluster[0] 
  vars:
    MASTER_VOL: rhv-sd1
    PRIMARY_SLAVE_HOST: dr-gluster01.example.com
    SLAVE_VOL: rhv-sd1-dr
    
  tasks:
    - name: Ensure {{ SLAVE_VOL }} is in read-only mode
      command: gluster volume set {{ SLAVE_VOL }} features.read-only on

    - name: Disabling indexing
      command: "gluster volume reset {{ SLAVE_VOL }} geo-replication.indexing force"
    
    - name: Disabling changelog
      command: "gluster volume set {{ SLAVE_VOL }} changelog"


- hosts: DR-RHVM
  vars:
    ansible_user: root

  tasks:
    - name: Ensure ovirt-engine is active
      systemd:
        state: started
        name: ovirt-engine

