---
- hosts: DR-Gluster[0]
  tags:
    - fail_over
  gather_facts: no
  vars: 
     slave_vols: rhv-sd1-dr 

  tasks:
  - name: Gluster tasks
    import_role:
      name: gluster
      tasks_from: failover.yml

- hosts: DR-RHVH[0]
  tags:
    - fail_over 
  gather_facts: no

  tasks:
  - name: Release SD locks (only for demo)
    import_role:
      name: gluster
      tasks_from: release_lock.yml
      

